import type { App } from "vue";
import PrimeVue from "primevue/config";
import Aura from "@primeuix/themes/aura";
// import Chart from 'primevue/chart';
import Button from "primevue/button";
import Checkbox from "primevue/checkbox";
import Column from "primevue/column";
import ColumnGroup from "primevue/columngroup";
import DataTable from "primevue/datatable";
import Dialog from "primevue/dialog";
import InputText from "primevue/inputtext";
import InputGroup from "primevue/inputgroup";
import Row from "primevue/row";
import Calendar from "primevue/calendar";
import ProgressBar from "primevue/progressbar";
import OverlayPanel from "primevue/overlaypanel";
import ContextMenu from "primevue/contextmenu";
import Tag from "primevue/tag";
import Menu from "primevue/menu";
import TieredMenu from "primevue/tieredmenu";
import Password from "primevue/password";
import RadioButton from "primevue/radiobutton";
import Splitter from "primevue/splitter";
import SplitterPanel from "primevue/splitterpanel";
import Textarea from "primevue/textarea";
import Tree from "primevue/tree";
import FileUpload from "primevue/fileupload";
import ToastService from "primevue/toastservice";
import ConfirmationService from "primevue/confirmationservice";
import Steps from "primevue/steps";
import InputNumber from "primevue/inputnumber";
import InputSwitch from "primevue/inputswitch";
import Dropdown from "primevue/dropdown";
import Slider from "primevue/slider";
import SpeedDial from "primevue/speeddial";
import InlineMessage from "primevue/inlinemessage";
import Card from "primevue/card";
import ProgressSpinner from "primevue/progressspinner";
import SplitButton from "primevue/splitbutton";
import TreeTable from "primevue/treetable";
import Tooltip from "primevue/tooltip";
import Message from "primevue/message";
import Sidebar from "primevue/sidebar";
import MultiSelect from "primevue/multiselect";
import Listbox from "primevue/listbox";
import ColorPicker from "primevue/colorpicker";
import Panel from "primevue/panel";
import ToggleButton from "primevue/togglebutton";
import ToggleSwitch from "primevue/toggleswitch";
import SelectButton from "primevue/selectbutton";
import Select from "primevue/select";
import InputIcon from "primevue/inputicon";
import IconField from "primevue/iconfield";
import Tabs from "primevue/tabs";
import TabList from "primevue/tablist";
import Tab from "primevue/tab";
import TabPanels from "primevue/tabpanels";
import TabPanel from "primevue/tabpanel";
import Chip from "primevue/chip";
import Accordion from "primevue/accordion";
import AccordionPanel from "primevue/accordionpanel";
import AccordionHeader from "primevue/accordionheader";
import AccordionContent from "primevue/accordioncontent";
import Stepper from "primevue/stepper";
import StepList from "primevue/steplist";
import StepPanels from "primevue/steppanels";
import StepItem from "primevue/stepitem";
import Step from "primevue/step";
import StepPanel from "primevue/steppanel";
import Avatar from "primevue/avatar";
import OverlayBadge from "primevue/overlaybadge";
import Divider from "primevue/divider";
import DatePicker from "primevue/datepicker";
import Paginator from "primevue/paginator";

const plugin = {
  install(app: App): void {
    app.use(PrimeVue, {
      theme: {
        preset: Aura
      },
      ripple: true
    });
    app.use(ConfirmationService);
    app.use(ToastService);
    app.directive("tooltip", Tooltip);

    app.component("pr-button", Button);
    app.component("pr-checkbox", Checkbox);
    app.component("pr-context-menu", ContextMenu);
    app.component("pr-dialog", Dialog);
    app.component("pr-dropdown", Dropdown);
    app.component("pr-input-text", InputText);
    app.component("pr-input-group", InputGroup);
    app.component("pr-password", Password);
    app.component("pr-input-number", InputNumber);
    app.component("pr-calendar", Calendar);
    app.component("pr-textarea", Textarea);
    app.component("pr-data-table", DataTable);
    app.component("pr-row", Row);
    app.component("pr-column", Column);
    app.component("pr-column-group", ColumnGroup);
    app.component("pr-progress-bar", ProgressBar);
    app.component("pr-overlay-panel", OverlayPanel);
    app.component("pr-tag", Tag);
    app.component("pr-menu", Menu);
    app.component("pr-tiered-menu", TieredMenu);
    app.component("pr-splitter", Splitter);
    app.component("pr-splitter-panel", SplitterPanel);
    app.component("pr-tree", Tree);
    app.component("pr-radio-button", RadioButton);
    app.component("pr-tabs", Tabs);
    app.component("pr-tab-list", TabList);
    app.component("pr-tab", Tab);
    app.component("pr-tab-panels", TabPanels);
    app.component("pr-tab-panel", TabPanel);
    app.component("pr-steps", Steps);
    app.component("pr-file-upload", FileUpload);
    app.component("pr-input-switch", InputSwitch);
    // app.component('pr-chart', Chart);
    app.component("pr-accordion", Accordion);
    app.component("pr-accordion-panel", AccordionPanel);
    app.component("pr-accordion-header", AccordionHeader);
    app.component("pr-accordion-content", AccordionContent);
    app.component("pr-slider", Slider);
    app.component("pr-speed-dial", SpeedDial);
    app.component("pr-inline-message", InlineMessage);
    app.component("pr-card", Card);
    app.component("pr-progress-spinner", ProgressSpinner);
    app.component("pr-split-button", SplitButton);
    app.component("pr-tree-table", TreeTable);
    app.component("pr-message", Message);
    app.component("pr-sidebar", Sidebar);
    app.component("pr-multi-select", MultiSelect);
    app.component("pr-list-box", Listbox);
    app.component("pr-color-picker", ColorPicker);
    app.component("pr-panel", Panel);
    app.component("pr-toggle-button", ToggleButton);
    app.component("pr-toggle-switch", ToggleSwitch);
    app.component("pr-select-button", SelectButton);
    app.component("pr-select", Select);
    app.component("pr-input-icon", InputIcon);
    app.component("pr-icon-field", IconField);
    app.component("pr-chip", Chip);
    app.component("pr-stepper", Stepper);
    app.component("pr-step-list", StepList);
    app.component("pr-step-panels", StepPanels);
    app.component("pr-step-item", StepItem);
    app.component("pr-step", Step);
    app.component("pr-step-panel", StepPanel);
    app.component("pr-avatar", Avatar);
    app.component("pr-overlay-badge", OverlayBadge);
    app.component("pr-divider", Divider);
    app.component("pr-date-picker", DatePicker);
    app.component("pr-paginator", Paginator);
  }
};

export default plugin;
